name: Run Selenium Tests

on: 
  workflow_dispatch:
    inputs:
      testFile:
        description: 'TestNG XML file to run'
        required: true
        default: 'testing.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Maven build
      run: mvn -B package --file pom.xml

    - name: Run Selenium tests
      run: mvn test -DsuiteXmlFile=${{ github.event.inputs.testFile }}
