name: Run Selenium Tests

on: 
  workflow_dispatch:
    inputs:
      testFile:
        description: 'TestNG XML file to run'
        required: true
        default: 'testing.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Maven build
      run: mvn -B package --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run Selenium tests
      run: mvn -B clean test -f pom.xml -DsuiteXmlFile=${{ github.event.inputs.testFile }} -Dtest.group=${{ github.event.inputs.testFile }}


  generate-reports:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Generate Allure Reports
      run: |
        mvn allure:report
    - name: Archive Allure Reports
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven-plugin
